name: Release plugins
on:
  push:
    branches:
      - master
      - dev
jobs:
  build:
    name: Release plugins
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Composer install
        run: |
          composer install --working-dir=./packages/waas-client
          composer install --working-dir=./packages/waas-host
      - name: Build release assets
        run: ./scripts/build.sh
      - name: Get release version
        run: echo "release_version=$(jq -r .version ./release.json)" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.release_version }}
          release_name: Release ${{ steps.vars.outputs.release_version }}
          draft: false
          prerelease: false
      - name: Upload Release assets
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./build/wpcs-waas-client.zip
          asset_name: wpcs-waas-client.zip
          asset_content_type: application/zip
      - name: Upload Release assets 2
        id: upload-release-assets-2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./build/wpcs-waas-host.zip
          asset_name: wpcs-waas-host.zip
          asset_content_type: application/zip
      - name: Upload Release assets 3
        id: upload-release-assets-3
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./build/wpcs-waas-client-info.json
          asset_name: wpcs-waas-client-info.json
          asset_content_type: application/json
      - name: Upload Release assets 4
        id: upload-release-assets-4
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./build/wpcs-waas-host-info.json
          asset_name: wpcs-waas-host-info.json
          asset_content_type: application/json
